services:
  restapi:
    build:
      context: ./RestApi
      dockerfile: Dockerfile
      args:
        DT_CODEMODULES_IMAGE: ${DT_CODEMODULES_IMAGE}
    ports:
      - "8080:8080"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jmeter

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false